### ISSUE TITLE
ValueError: Exception encountered when calling layer "model" (type Functional)

### ISSUE THREAD

**Issue by CscotfordMV** [HasnainRaz/Fast-SRGAN#48]
Trying to run this model on Google Colab with a general-sized image (i.e., not 96x96) and I hit the above error. I have implemented the suggested code block to generalise to arbitrary sized images and ran the suggested code to apply the model. The traceback is given by:

```
Traceback (most recent call last):
  File "infer.py", line 50, in <module>
    main()
  File "infer.py", line 37, in main
    sr = model.predict(np.expand_dims(low_res, axis=0))[0]
  File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/tmp/__autograph_generated_filealp9pr7w.py", line 15, in tf__predict_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
ValueError: in user code:

    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1845, in predict_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1834, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1823, in run_step  **
        outputs = model.predict_step(data)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1791, in predict_step
        return self(x, training=False)
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/input_spec.py", line 264, in assert_input_compatibility
        raise ValueError(f'Input {input_index} of layer "{layer_name}" is '

    ValueError: Exception encountered when calling layer "model" (type Functional).
    
    Input 0 of layer "model_2" is incompatible with the layer: expected shape=(None, 96, 96, 3), found shape=(None, 1600, 1178, 3)
    
    Call arguments received by layer "model" (type Functional):
      • inputs=tf.Tensor(shape=(None, 1600, 1178, 3), dtype=float32)
      • training=False
      • mask=None
```

**Comment by davlee1972** [comment]
I made a pull request to fix infer.py for tensorflow==2.11.0

Pull Request - https://github.com/HasnainRaz/Fast-SRGAN/pull/50

Code Changes - https://github.com/HasnainRaz/Fast-SRGAN/pull/50/commits/7c2e7c65d1c53c9f163efcf2a207e7b94a9f7445

Alternatively you can just save the new model and just use it for keras.models.load_model.

```
    model = keras.models.load_model('models/generator.h5')
    model = change_model(model, new_input_shape=[None, None, None, 3])
    keras.models.save_model(model, 'models/new_generator.h5')
```

**Comment by HasnainRaz** [comment]
Since I'm not bumping tf version for now, I assume @davlee1972 's fix is enough, closing

**Comment by vinayakSharm** [comment]
> Since I'm not bumping tf version for now, I assume @davlee1972 's fix is enough, closing

I think that the code should always be running the latest version of tf. As a user, I think its best if this functionality was integrated into the code base!

**Comment by HasnainRaz** [comment]
@viI empathize with your view, but there are two problems:

1. I currently do not have time to maintain the project
2. TFs versions have seen some drastic breaking changes since the time this was first released.

If you are willing to, I'm happy to accept PRs that bump TF versions while making sure the code doesn't break.
